# Perfil MySQL opcional para usar base de datos local techshop
spring.datasource.url=jdbc:mysql://localhost:3306/techshop
spring.datasource.username=usuario_prueba
spring.datasource.password=Usuarlo_Clave.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
