spring.application.name=tienda

#Para definir el puerto donde "escuchara" el servidor
#80 requiere privilegios en muchos sistemas; 8080 evita ese bloqueo en local.
server.port=8080

#Para definir el formato de despliegue de fecha/hora del log en la consola
logging.pattern.dateformat=hh:mm

#Para eliminar mensajes invasivos de Spring
spring.main.banner-mode=off

#En desarrollo el "cache" del servidor (false), en produccion "true"
spring.thymeleaf.cache=false

#Conexión local por defecto (H2 en memoria) para facilitar pruebas en localhost
spring.datasource.url=jdbc:h2:mem:techshop;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#mostrar información en el log
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.type.descriptor.sql.BasicBinder=TRACE

firebase.enabled=false
firebase.bucket.name=techshop-80f5b.firebasestorage.app
firebase.storage.path=techshop
firebase.json.path=firebase
firebase.json.file=techshop-80f5b-firebase-adminsdk-fbsvc-dd2e28eb30.json
